<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUW3A2dU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUW3A2dU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUW3A2dU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUW3A2dU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUW3A2dU\App_KernelDevDebugContainer([
    'container.build_hash' => 'UW3A2dU',
    'container.build_id' => '0f0138df',
    'container.build_time' => 1653033274,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUW3A2dU');
