<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXhHIOpo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXhHIOpo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXhHIOpo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXhHIOpo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXhHIOpo\App_KernelDevDebugContainer([
    'container.build_hash' => 'XhHIOpo',
    'container.build_id' => 'ab2b146c',
    'container.build_time' => 1653385402,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXhHIOpo');
